disabled_rules: # rule identifiers turned on by default to exclude from running
  - force_cast
  - force_try
  - identifier_name
  - multiple_closures_with_trailing_closure
  - opening_brace
  - redundant_string_enum_value
  - type_name
  - trailing_whitespace

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

cyclomatic_complexity:
  ignores_case_statements: true

file_length: 1000
line_length:
  warning: 150
  error: 300
  ignores_urls: true
  ignores_comments: true
  ignores_interpolated_strings: true
